src/Models/Endereco.cs
using System.ComponentModel.DataAnnotations;

namespace AppMVCBasica.Models;

public class Endereco : Entity
{
    public Guid FornecedorId { get; set; }

    [Required(ErrorMessage = "O campo {0} não pode ser vazio.")]
    [StringLength(200, ErrorMessage = "O campo {0} precisa ter entre {2} e {1} caracteres.", MinimumLength = 2)]
    public string? Logradouro { get; set; }

    [Required(ErrorMessage = "O campo {0} não pode ser vazio.")]
    [StringLength(50, ErrorMessage = "O campo {0} precisa ter entre {2} e {1} caracteres.", MinimumLength = 1)]
    public string? Numero { get; set; }
    public string? Complemento { get; set; }

    [Required(ErrorMessage = "O campo {0} não pode ser vazio.")]
    [StringLength(8, ErrorMessage = "O campo {0} precisa ter {1} caracteres.", MinimumLength = 8)]
    public string? Cep { get; set; }

    [Required(ErrorMessage = "O campo {0} não pode ser vazio.")]
    [StringLength(100, ErrorMessage = "O campo {0} precisa ter entre {2} e {1} caracteres.", MinimumLength = 2)]
    public string? Bairro { get; set; }

    [Required(ErrorMessage = "O campo {0} não pode ser vazio.")]
    [StringLength(100, ErrorMessage = "O campo {0} precisa ter entre {2} e {1} caracteres.", MinimumLength = 2)]
    public string? Cidade { get; set; }

    [Required(ErrorMessage = "O campo {0} não pode ser vazio.")]
    [StringLength(50, ErrorMessage = "O campo {0} precisa ter entre {2} e {1} caracteres.", MinimumLength = 2)]
    public string? Estado { get; set; }

    /* EF Relations */
    public Fornecedor? Fornecedor { get; set; }
}

src/Models/Entity.cs
namespace AppMVCBasica.Models;

public abstract class Entity
{
    protected Entity()
    {
        Id = Guid.NewGuid();
        DataCadastro = DateTime.Now;
    }
    public Guid Id { get; set; }
    public DateTime DataCadastro { get; set; }
}

src/Models/ErrorViewModel.cs
namespace AppMVCBasica.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

src/Models/Fornecedor.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace AppMVCBasica.Models;

public class Fornecedor : Entity
{
    [Required(ErrorMessage = "O campo {0} não pode ser vazio.")]
    [StringLength(100, ErrorMessage = "O campo {0} precisa ter entre {2} e {1} caracteres.", MinimumLength = 2)]
    public string? Nome { get; set; }

    [Required(ErrorMessage = "O campo {0} não pode ser vazio.")]
    [StringLength(14, ErrorMessage = "O campo {0} precisa ter entre {2} e {1} caracteres.", MinimumLength = 11)]
    public string? Documento { get; set; }
    public TipoFornecedor TipoFornecedor { get; set; }
    public Endereco? Endereco { get; set; }

    [DisplayName("Ativo?")]
    public bool Ativo { get; set; }

    /* EF Relations */
    public IEnumerable<Produto>? Produtos { get; set; }
}

src/Models/Produto.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace AppMVCBasica.Models;

public class Produto : Entity
{
    public Guid FornecedorId { get; set; }

    [Required(ErrorMessage = "O campo {0} não pode ser vazio.")]
    [StringLength(200, ErrorMessage = "O campo {0} precisa ter entre {2} e {1} caracteres.", MinimumLength = 2)]
    public string? Nome { get; set; }

    [Required(ErrorMessage = "O campo {0} não pode ser vazio.")]
    [StringLength(1000, ErrorMessage = "O campo {0} precisa ter entre {2} e {1} caracteres.", MinimumLength = 2)]
    public string? Descricao { get; set; }

    [Required(ErrorMessage = "O campo {0} não pode ser vazio.")]
    [StringLength(200, ErrorMessage = "O campo {0} precisa ter entre {2} e {1} caracteres.", MinimumLength = 2)]
    public string? Imagem { get; set; }

    [Required(ErrorMessage = "O campo {0} não pode ser vazio.")]
    public decimal Valor { get; set; }

    [DisplayName("Ativo?")]
    public bool Ativo { get; set; }

    /* EF Relations */
    public Fornecedor? Fornecedor { get; set; }
}

src/Models/TipoFornecedor.cs
namespace AppMVCBasica.Models;

public enum TipoFornecedor
{
    PessoaFisica = 1,
    PessoaJuridica = 2
}

src/Controllers/FornecedoresController.cs
using AppMVCBasica.Data;
using AppMVCBasica.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace AppMVCBasica.Controllers;

[Route("api/[controller]")]
public class FornecedoresController : Controller
{
    private readonly ApplicationDbContext _context;

    public FornecedoresController(ApplicationDbContext context)
    {
        _context = context;
    }

    [HttpGet]
    public async Task<IActionResult> Index()
    {
        return View(await _context.Fornecedores.ToListAsync());
    }

    [HttpGet("{id}")]
    public async Task<IActionResult> GetOne(Guid? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var fornecedor = await _context.Fornecedores
            .FirstOrDefaultAsync(predicate:m => m.Id == id);
        if (fornecedor == null)
        {
            return NotFound();
        }

        return View(fornecedor);
    }

    [HttpPost]
    public async Task<IActionResult> Create(Fornecedor fornecedor)
    {
        if (ModelState.IsValid)
        {
            _context.Add(fornecedor);
            await _context.SaveChangesAsync();
            return RedirectToAction(actionName:nameof(Index));
        }
        return View(fornecedor);
    }

    [HttpPut("{id}")]
    public async Task<IActionResult> Edit(Guid? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var fornecedor = await _context.Fornecedores.FindAsync(id);
        if (fornecedor == null)
        {
            return NotFound();
        }

        return View(fornecedor);
    }

    [HttpPut("{id}")]
    public async Task<IActionResult> Edit(Guid? id, Fornecedor fornecedor)
    {
        if (id != fornecedor.Id)
        {
            return NotFound();
        }

        if (ModelState.IsValid)
        {
            try
            {
                _context.Update(fornecedor);
                await _context.SaveChangesAsync();
            }
            catch(DbUpdateConcurrencyException)
            {
                if (!FornecedorExists(fornecedor.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            return RedirectToAction(actionName: nameof(Index));
        }

        return View(fornecedor);
    }

    [HttpDelete("{id}")]
    public async Task<IActionResult> Delete(Guid? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var fornecedor = await _context.Fornecedores
            .FirstOrDefaultAsync(predicate: m => m.Id == id);
        if (fornecedor == null)
        {
            return NotFound();
        }

        return View(fornecedor);
    }

    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteConfirmed(Guid? id)
    {
        var fornecedor = await _context.Fornecedores.FindAsync(id);
        _context.Fornecedores.Remove(fornecedor);
        await _context.SaveChangesAsync();
        return RedirectToAction(actionName: nameof(Index));
    }

    private bool FornecedorExists(Guid id)
    {
        return _context.Fornecedores.Any(e => e.Id == id);
    }
}

src/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using AppMVCBasica.Models;

namespace src.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

src/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

src/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - src</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/src.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">src</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - src - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

src/Views/Fornecedores/Create.cshtml
@model AppMVCBasica.Models.Fornecedor

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Fornecedor</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Documento" class="control-label"></label>
                <input asp-for="Documento" class="form-control" />
                <span asp-validation-for="Documento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TipoFornecedor" class="control-label"></label><br />
                <input type="radio" value="1" asp-for="TipoFornecedor" checked /> Pessoa Física<br />
                <input type="radio" value="2" asp-for="TipoFornecedor" /> Pessoa Jurídica
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Ativo" /> @Html.DisplayNameFor(model => model.Ativo)
                </label>
            </div>
            
            <hr/>
            <h4>Endereço</h4>
            
            <partial name="_Endereco"/>

            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/Views/Fornecedores/Delete.cshtml
@model AppMVCBasica.Models.Fornecedor

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Fornecedor</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Documento)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Documento)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TipoFornecedor)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TipoFornecedor)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Ativo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Ativo)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

src/Views/Fornecedores/Details.cshtml
@model AppMVCBasica.Models.Fornecedor

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Fornecedor</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Documento)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Documento)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TipoFornecedor)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TipoFornecedor)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Ativo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Ativo)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

src/Views/Fornecedores/Edit.cshtml
@model AppMVCBasica.Models.Fornecedor

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Fornecedor</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Documento" class="control-label"></label>
                <input asp-for="Documento" class="form-control" />
                <span asp-validation-for="Documento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TipoFornecedor" class="control-label"></label>
                <div>
                    <input type="radio" value="1" asp-for="TipoFornecedor" checked="@((int)Model.TipoFornecedor == 1)" /> Pessoa Física
                    <input type="radio" value="2" asp-for="TipoFornecedor" checked="@((int)Model.TipoFornecedor == 2)" /> Pessoa Jurídica
                </div>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Ativo" /> @Html.DisplayNameFor(model => model.Ativo)
                </label>
            </div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/Views/Fornecedores/Index.cshtml
@model IEnumerable<AppMVCBasica.Models.Fornecedor>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Documento)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TipoFornecedor)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Ativo)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Documento)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TipoFornecedor)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Ativo)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

src/Views/Fornecedores/_Endereco.cshtml
@model AppMVCBasica.Models.Fornecedor

            <div class="form-group">
                <label asp-for="Endereco.Logradouro" class="control-label"></label>
                <input asp-for="Endereco.Logradouro" class="form-control" />
                <span asp-validation-for="Endereco.Logradouro" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Endereco.Numero" class="control-label"></label>
                <input asp-for="Endereco.Numero" class="form-control" />
                <span asp-validation-for="Endereco.Numero" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Endereco.Complemento" class="control-label"></label>
                <input asp-for="Endereco.Complemento" class="form-control" />
                <span asp-validation-for="Endereco.Complemento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Endereco.Cep" class="control-label"></label>
                <input asp-for="Endereco.Cep" class="form-control" />
                <span asp-validation-for="Endereco.Cep" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Endereco.Bairro" class="control-label"></label>
                <input asp-for="Endereco.Bairro" class="form-control" />
                <span asp-validation-for="Endereco.Bairro" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Endereco.Cidade" class="control-label"></label>
                <input asp-for="Endereco.Cidade" class="form-control" />
                <span asp-validation-for="Endereco.Cidade" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Endereco.Estado" class="control-label"></label>
                <input asp-for="Endereco.Estado" class="form-control" />
                <span asp-validation-for="Endereco.Estado" class="text-danger"></span>
            </div>
           

src/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

src/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - src</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/src.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">src</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Fornecedores" asp-action="Index">Fornecedores</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - src - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>